# Generated by Django 2.2.10 on 2020-05-05 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('schedule_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('schedulebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedules.ScheduleBase')),
            ],
            bases=('schedules.schedulebase',),
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Start time')),
                ('end', models.TimeField(verbose_name='End time')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Task')),
                ('day_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.DaySchedule')),
            ],
        ),
    ]
